name: dialink
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  dio: ^5.7.0
  provider: ^6.1.2
  talker_logger: ^4.6.6
  json_annotation: ^4.9.0
  iconsax: ^0.0.8
  flutter_secure_storage: ^9.2.4
  pin_code_text_field: ^1.8.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Cooper BT
      fonts:
        - asset: fonts/CooperLtBT-Bold.ttf
          weight: 700
        - asset: fonts/CooperLtBT-Regular.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Regular.ttf
         
